export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const ADD_ENTRY = 'ADD_ENTRY';
export const GET_LATEST_ENTRIES = 'GET_LATEST_ENTRIES';
export const GET_LATEST_ENTRIES_FAILURE = 'GET_LATEST_ENTRIES_FAILURE';
export const DASH_DEFAULT = 'DASH_DEFAULT';
