export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const DASH_DEFAULT = 'DASH_DEFAULT';
export const ADD_ENTRY = 'ADD_ENTRY';
export const EDIT_ENTRY = 'EDIT_ENTRY';

export const GET_LATEST_ENTRIES = 'GET_LATEST_ENTRIES';
export const GET_LATEST_ENTRIES_FAILURE = 'GET_LATEST_ENTRIES_FAILURE';

export const LOADING_START = 'LOADING_START';
export const LOADING_STOP = 'LOADING_STOP';

export const DELETE_ENTRY = 'DELETE_ENTRY';
export const DELETE_ENTRY_FAILURE = 'DELETE_ENTRY_FAILURE';